In [1]:
import pandas as pd
import numpy as np

In [2]:
real_news = pd.read_csv('true.csv')
fake_news = pd.read_csv('fake.csv')

In [3]:
real_news['label'] = 0
fake_news['label'] = 1

In [4]:
real_news

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",0
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",0
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",0
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",0
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",0
...,...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",0
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",0
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",0
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",0
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",0

In [5]:
fake_news

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",1
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",1
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",1
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",1
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",1
...,...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",1
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",1
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",1
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",1
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",1

In [6]:
dataset1 = real_news[['text', 'label']]
dataset2 = fake_news[['text', 'label']]

In [7]:
dataset1

                                                    text  label
0      WASHINGTON (Reuters) - The head of a conservat...      0
1      WASHINGTON (Reuters) - Transgender people will...      0
2      WASHINGTON (Reuters) - The special counsel inv...      0
3      WASHINGTON (Reuters) - Trump campaign adviser ...      0
4      SEATTLE/WASHINGTON (Reuters) - President Donal...      0
...                                                  ...    ...
21412  BRUSSELS (Reuters) - NATO allies on Tuesday we...      0
21413  LONDON (Reuters) - LexisNexis, a provider of l...      0
21414  MINSK (Reuters) - In the shadow of disused Sov...      0
21415  MOSCOW (Reuters) - Vatican Secretary of State ...      0
21416  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...      0

[21417 rows x 2 columns]

In [8]:
dataset2

                                                    text  label
0      Donald Trump just couldn t wish all Americans ...      1
1      House Intelligence Committee Chairman Devin Nu...      1
2      On Friday, it was revealed that former Milwauk...      1
3      On Christmas day, Donald Trump announced that ...      1
4      Pope Francis used his annual Christmas Day mes...      1
...                                                  ...    ...
23476  21st Century Wire says As 21WIRE reported earl...      1
23477  21st Century Wire says It s a familiar theme. ...      1
23478  Patrick Henningsen  21st Century WireRemember ...      1
23479  21st Century Wire says Al Jazeera America will...      1
23480  21st Century Wire says As 21WIRE predicted in ...      1

[23481 rows x 2 columns]

In [9]:
dataset = pd.concat([dataset1, dataset2])

In [10]:
dataset

                                                    text  label
0      WASHINGTON (Reuters) - The head of a conservat...      0
1      WASHINGTON (Reuters) - Transgender people will...      0
2      WASHINGTON (Reuters) - The special counsel inv...      0
3      WASHINGTON (Reuters) - Trump campaign adviser ...      0
4      SEATTLE/WASHINGTON (Reuters) - President Donal...      0
...                                                  ...    ...
23476  21st Century Wire says As 21WIRE reported earl...      1
23477  21st Century Wire says It s a familiar theme. ...      1
23478  Patrick Henningsen  21st Century WireRemember ...      1
23479  21st Century Wire says Al Jazeera America will...      1
23480  21st Century Wire says As 21WIRE predicted in ...      1

[44898 rows x 2 columns]

In [11]:
dataset.shape

(44898, 2)

In [12]:
dataset.isnull().sum()

text     0
label    0
dtype: int64

In [13]:
dataset['label'].value_counts()

label
1    23481
0    21417
Name: count, dtype: int64

In [14]:
dataset = dataset.sample(frac = 1)

In [15]:
dataset

                                                    text  label
17796  BANGKOK (Reuters) - Thailand is putting the fi...      0
6939   WASHINGTON (Reuters) - The U.S. House of Repre...      0
10838  (Reuters) - U.S. Supreme Court Justice Antonin...      0
5143   NEW YORK (Reuters) - Environmentally conscious...      0
2659   Among the never ending stream of Trump adminis...      1
...                                                  ...    ...
14150  On March 20, 2016 Barkley had this to say abou...      1
11379  BEIJING (Reuters) - China sentenced a prominen...      0
7689   UNITED NATIONS (Reuters) - The United States o...      0
4377   How would you feel if you found out that your ...      1
5249   WASHINGTON (Reuters) - U.S. President Donald T...      0

[44898 rows x 2 columns]

# NLP

In [16]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [17]:
ps = WordNetLemmatizer()

In [18]:
stopwords = stopwords.words('english')

In [19]:
def clean_row_dataset(row):
    row = row.lower()
    row = re.sub('[^a-zA-Z]', ' ', row)
    token = row.split()
    news = [ps.lemmatize(word) for word in token if not word in stopwords]
    cleanned_news = ' '.join(news)
    return cleanned_news

In [20]:
dataset['text']

17796    BANGKOK (Reuters) - Thailand is putting the fi...
6939     WASHINGTON (Reuters) - The U.S. House of Repre...
10838    (Reuters) - U.S. Supreme Court Justice Antonin...
5143     NEW YORK (Reuters) - Environmentally conscious...
2659     Among the never ending stream of Trump adminis...
                               ...
14150    On March 20, 2016 Barkley had this to say abou...
11379    BEIJING (Reuters) - China sentenced a prominen...
7689     UNITED NATIONS (Reuters) - The United States o...
4377     How would you feel if you found out that your ...
5249     WASHINGTON (Reuters) - U.S. President Donald T...
Name: text, Length: 44898, dtype: str

In [21]:
dataset['text'] = dataset['text'].apply(lambda x : clean_row_dataset(x))

In [22]:
dataset['text']

17796    bangkok reuters thailand putting finishing tou...
6939     washington reuters u house representative pass...
10838    reuters u supreme court justice antonin scalia...
5143     new york reuters environmentally conscious inv...
2659     among never ending stream trump administration...
                               ...
14150    march barkley say obama listen people america ...
11379    beijing reuters china sentenced prominent righ...
7689     united nation reuters united state wednesday a...
4377     would feel found child educated insanely racis...
5249     washington reuters u president donald trump pi...
Name: text, Length: 44898, dtype: str

In [23]:
X = dataset.iloc[:44898, 0]
y = dataset.iloc[:44898, 1]

In [24]:
X

17796    bangkok reuters thailand putting finishing tou...
6939     washington reuters u house representative pass...
10838    reuters u supreme court justice antonin scalia...
5143     new york reuters environmentally conscious inv...
2659     among never ending stream trump administration...
                               ...
14150    march barkley say obama listen people america ...
11379    beijing reuters china sentenced prominent righ...
7689     united nation reuters united state wednesday a...
4377     would feel found child educated insanely racis...
5249     washington reuters u president donald trump pi...
Name: text, Length: 44898, dtype: str

In [25]:
y

17796    0
6939     0
10838    0
5143     0
2659     1
        ..
14150    1
11379    0
7689     0
4377     1
5249     0
Name: label, Length: 44898, dtype: int64

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
train_data, test_data, train_label, test_label = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [29]:
vectorizer = TfidfVectorizer(max_features=50000, lowercase=False, ngram_range=(1, 2))

In [30]:
vec_train_data = vectorizer.fit_transform(train_data)

In [31]:
vec_test_data = vectorizer.transform(test_data)

In [32]:
vec_train_data.shape, vec_test_data.shape

((35918, 50000), (8980, 50000))

# Model

In [33]:
from sklearn.linear_model import LogisticRegression

In [34]:
classifier = LogisticRegression(random_state = 42)

In [35]:
classifier.fit(vec_train_data, train_label)

LogisticRegression(random_state=42)

In [36]:
y_pred_test = classifier.predict(vec_test_data)

In [37]:
y_pred_train = classifier.predict(vec_train_data)

In [38]:
from sklearn.metrics import accuracy_score

In [39]:
accuracy_score(test_label, y_pred_test)

0.9881959910913141